students = [
    {'aluno': 'Douglas', 'nota': 10},
    {'aluno': 'Maria', 'nota': 8},
    {'aluno': 'Tales', 'nota': 6},
    {'aluno': 'Carol', 'nota': 9},
    {'aluno': 'Gerson', 'nota': 4},
    {'aluno': 'Kaila', 'nota': 2},
    {'aluno': 'Maicon', 'nota': 7},
    {'aluno': 'Lorenzo', 'nota': 6},
    {'aluno': 'Talita', 'nota': 7},
    {'aluno': 'Amanda', 'nota': 5},
    {'aluno': 'Helio', 'nota': 0},
    {'aluno': 'Fabio', 'nota': 0},
    {'aluno': 'Wesley', 'nota': 10},
]
